name: SwiftLint Analyze

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/swiftlint_analyze.yml'
      - 'InterposeKit.xcodeproj/**'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - '!Tests/**/*.swift'
      - '!Tests/LinuxMain.swift'
  pull_request:
    paths:
      - '.github/workflows/swiftlint_analyze.yml'
      - 'InterposeKit.xcodeproj/**'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - '!Tests/**/*.swift'
      - '!Tests/LinuxMain.swift'

jobs:
  Analyze:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    steps:
      - uses: actions/checkout@v2
      - name: Generate xcodebuild.log
        run: xcodebuild -scheme InterposeKit -project InterposeKit.xcodeproj clean build-for-testing > xcodebuild.log
        shell: bash
      - name: Install SwiftLint
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.github.com/Homebrew/homebrew-core/master/Formula/swiftlint.rb
      - name: Run SwiftLint Analyze
        run: swiftlint analyze --strict --compiler-log-path xcodebuild.log --reporter github-actions-logging
